# Generated by Django 3.2.5 on 2021-10-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('Latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
        ),
    ]
